language: bash

services:
  - docker

env:
  global:
    - IMAGE_NAME=fulgensailurus/account_service

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker run --rm "$IMAGE_NAME" npm run test || travis_terminate 1
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
